### PR TITLE
No configuration found when is used with git hook

### PR DESCRIPTION
**Pull request by sergio-alonso**
Files with changes are moved to a temporal directory when flake8 git hook is used.

$ flake8 --install-hook git

flake8-isort should look for configuration files in the current directory while checking the files in the temporary directory.

Before fix, no configuration is found.

$ git commit -m "Commit message"
script.py:0:1: I002 no configuration found (.isort.cfg or [isort] on setup.cfg)

After fix, project configuration is found.

$ git commit -m "Commit message"
script.py:1:1: D200 One-line docstring should fit on one line with quotes

### CODE REVIEW

**Comment by gforcada** [comment]
@sergio-alonso hi! thanks for the pull request! travis is failing due to a flake8 error, would you mind fixing it so that we can check if tests do pass after your changes? Thanks in advance!

**Comment by gforcada** [comment]
@sergio-alonso thanks for fixing it!

Now that I check in more detail I did not know that flake8 had a way to integrate with git/mercurial, thanks for pointing that out!

Two last things:
- would you mind writing an entry on https://github.com/gforcada/flake8-isort/blob/master/CHANGES.rst so when I release a new version everywhere can see what has been changed and who did it?
- would you be up to write a test for it? If you take a look at https://github.com/gforcada/flake8-isort/blob/master/run_tests.py there are quite a few tests related to configuration files.

**Comment by sergio-alonso** [comment]
Hi @gforcada , I'm trying to figure out how to test it.

**Comment by gforcada** [comment]
@sergio-alonso any progress so far?

Looking at the code a bit more carefully I see that the code on ``search_isort_config_at_current`` method is the same the code in the loop on ``search_isort_config`` method. Would you mind if I take over your changes and extract that code into a method so code can be reused?

**Comment by gforcada** [comment]
I move it to #30 thanks for your work, I will try to release it during today or tomorrow.

**Comment by gforcada** [comment]
@sergio-alonso I made a new release (2.2) with your fix, would you mind giving it a try? thanks in advance.

**Comment by sergio-alonso** [comment]
Thanks @gforcada I will try it.

**Pull request closed without merging**
