### PR TITLE
Allow isort configuration through pyproject.toml

### PR DESCRIPTION
**Pull request by uyar**
This change fixes the -incorrectly- closed issue #71.

### CODE REVIEW

**Comment by uyar** [comment]
I'm not closing this PR just yet but the PR by @jnn looks better.

**Comment by uyar** [comment]
And if for some reason this PR gets preferred, I will rewrite the code to use tomlkit instead of toml since that is used in the isort project itself.

**Comment by gforcada** [comment]
@uyar and @jnns would you be ok with closing this one in favor of @jnns #79  ?

**Comment by uyar** [comment]
@gforcada @jnns Yes, I think this is the cleaner way. I checked #79 on one of my projects and it seems to work OK.

**Pull request closed without merging**
