### PR TITLE
Switch config behaviour for new Flake8 v3 API

### PR DESCRIPTION
**Pull request by danpalmer**
This addresses #13.

### CODE REVIEW

**Comment by Jc2k** [comment]
See https://gitlab.com/pycqa/flake8/blob/master/src/flake8/api/legacy.py for fixing the failing test.

Maybe

```
try:
    from flake8.engine import get_style_guide
except ImportError:
    from flake8.api.legacy import get_style_guide
```

?

**Comment by w0rp** [comment]
Would it be possible to get this fixed, merged, and published to PyPI? I just ran `pip install` to run this plugin and hit the same issue.

**Comment by danpalmer** [comment]
Just came across this while trying to find out why I couldn't upgrade flake8. Guess I dropped the ball on this pretty badly.

**Comment by gforcada** [comment]
@danpalmer thanks for keeping this ongoing, I'm curious why the tests that now fail do fail to begin with... something else must have changed on flake8 side... we need to check how stdin values are processed.

**Comment by danpalmer** [comment]
@gforcada so the issue is that the legacy API we're using here doesn't use argv, it doesn't allow any arguments at all. I think we need to figure out how to use the new API.

**Comment by danpalmer** [comment]
Ok, this should fix it. Beware that we're currently installing the latest version of `flake8` for tests, we might want to do a test run with both 2.x and 3.x using something like Tox. That change is outside the scope of this test though.

**Comment by gforcada** [comment]
@danpalmer I was thinking the same, because yesterday while testing it locally I had a problem on another part of the code as ``flake8.__version__`` does not exist on at least flake8 2.4.x

**Comment by danpalmer** [comment]
Hmm. I believe this is compatible with 2.6.2 and 3.0.4.

**Comment by gforcada** [comment]
so we can remove all conditional imports

**Comment by danpalmer** [comment]
@gforcada by all means, I'd be in favour of that, but could you organise that?

**Comment by gforcada** [comment]
@danpalmer sure, let me merge the code, then I will refactor it to my own taste and do a 2.0 release.I will try to get that either today or tomorrow but don't be shy to ping me again if I get distracted (you know ... family, kids and work :-)

**Comment by danpalmer** [comment]
Great, thanks!

**Comment by w0rp** [comment]
Thank you both for looking at this. Now I might try and get this plugin installed for use with my own work code base, where we use `isort` a lot.

**Pull request merged**
