### PR TITLE
Add support for pyproject.toml.

### LINKED ISSUE #71: Support for pyproject.toml
isort added support for using a `pyproject.toml` file for it's configuration in version 4.3.5. It would be great if this module could be compatible.

### PR DESCRIPTION
**Pull request by sanjioh**
Fixes #71

### CODE REVIEW

**Comment by gforcada** [comment]
@sanjioh  thanks for your contribution, it is finally released as `flake8-isort 2.8.0` :tada:

**Comment by uyar** [comment]
@gforcada @sanjioh This doesn't seem to be included in `flake8-isort 2.8.0`. There is no mention of `pyproject.toml` in the code. The commit only changes the `run_test` and `setup` modules, and not the `flake8_isort` module. Am I missing something?

**Comment by gforcada** [comment]
@uyar I thought so myself when I first tried this pull request locally, but (un)fortunately isort, as soon as there is `toml` available, it uses the pyproject.toml configuration if it is available.

It is good in a way, because without us here in flake8-isort doing anything it already works, but it makes all the configuration searching a bit pointless as isort, despite whatever you give as configuration, still looks for it on its own.

Or at least that's how I understood it, which can be totally wrong :sweat_smile:

**Comment by uyar** [comment]
@gforcada But it didn't work in my environment although toml was available. It failed due to configuration being missing and without calling isort. As least I think that's what happened. I'll check it out tomorrow and get back to you.

**Comment by uyar** [comment]
I think the current last comment on the closed issue #71 is correct.

**Comment by gforcada** [comment]
@uyar thanks for pointing that out, that comment somehow slipped through the cracks and I missed it :sweat:

**Pull request merged**
